/* Regression baseline (no longer a migration baseline).

   baseline.json was originally generated by running the engine of the first
   prototype (legacy/legacy-engine.html, L217-576) — it proved that the move to
   modules had changed nothing. It has since changed twice on purpose, each
   time for a deliberate behaviour change rather than a migration bug: the
   drawing resolution (0.5 m -> 0.1 m) and, more recently, evacuate() — it used
   to evacuate "in rounds" (a car could get out only because another one was
   assumed to have left first); now every car is checked independently, with
   all the others parked exactly where they are (no exit order taken for
   granted). See the comment on evacuate() in planner.js. baseline.json is
   regenerated by running THE CURRENT ENGINE against itself, and it acts as a
   regression line going forward: if a change to the planner or to the
   collision moves any of these numbers, this test has to say so — and then it
   is a decision whether the change was intended (regenerate the baseline) or a
   bug. */

import test from "node:test";
import assert from "node:assert/strict";
import baseline from "./baseline.json" with { type: "json" };
import { presets } from "../src/scene.js";
import { evacuate } from "../src/planner.js";
import { specOf } from "../src/vehicle.js";

const OPTS = baseline._opts;

for (const name of Object.keys(baseline).filter((k) => !k.startsWith("_"))) {
  test(`preset "${name}" reproduces the baseline`, async () => {
    const exp = baseline[name];
    const { world, cars } = presets[name]();

    assert.equal(world.cols, exp.cols, "floor plan width");
    assert.equal(world.rows, exp.rows, "floor plan depth");
    assert.equal(world.segs.length, exp.segs, "number of wall segments");
    assert.equal(cars.length, exp.cars.length, "number of cars");

    const r = await evacuate(world, cars, OPTS);

    for (const want of exp.cars) {
      const car = cars[want.i];
      const got = r.out.find((o) => o.id === car.id);
      const on = `${name} car ${want.i} (${want.model})`;

      assert.equal(specOf(car).name, want.model, `${on}: model`);

      if (want.ok) {
        assert.ok(got, `${on}: should get out and does not`);
        assert.equal(got.man, want.man, `${on}: manoeuvres`);
        assert.equal(+got.len.toFixed(2), want.len, `${on}: route length`);
      } else {
        assert.ok(!got, `${on}: should not get out and does`);
        assert.equal(r.diag[car.id]?.kind, want.kind, `${on}: diagnosis`);
      }
    }
  });
}
